export type { CampaignInsight, AccountSnapshot, AccountTotals, WindowSnapshot, Window } from "./meta";
export { WINDOWS } from "./meta";
export type { ClientConfig } from "./clients";

export type Severity = "info" | "warning" | "critical";

export interface Flag {
  title: string;
  detail: string;
  severity: Severity;
  campaignId?: string;
}

export interface Optimization {
  title: string;
  detail: string;
  expectedImpact?: string;
  campaignId?: string;
}

/** Structured health check for one client's account, as generated by Claude, covering all three windows at once. */
export interface ClientHealthCheck {
  clientId: string;
  clientName: string;
  healthStatus: "good" | "warning" | "critical";
  summary: string;
  keyNotes: string[];
  flags: Flag[];
  optimizations: Optimization[];
}

export interface InsightsResponse extends ClientHealthCheck {
  fetchedAt: string;
}

export interface DailyReport {
  generatedAt: string;
  clients: (ClientHealthCheck & { snapshot: import("./meta").AccountSnapshot })[];
}
